---
- name: Install texlive-core
  pacman:
    name: texlive-core
    state: present

- name: Install texlive-latexextra
  pacman:
    name: texlive-latexextra
    state: present

- name: Install GNU Plot
  pacman:
    name: gnuplot
    state: present